### ISSUE TITLE
Stage mitxonline `users_*` tables 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-data-platform#333]
# User Story

Stage data from mtixonline user tables, so the data is clean and we can combine them into a denormalized `users` table in the intermediate / warehouse layer

# Description/Context

- [x] #334
- [x] #335
- [x] #337
- [x] #338
- [x] #339
- [x] #336
- [x] #340

# Acceptance Criteria

for each table: 
- [ ] enumerate the fields
- [ ] write up a plan for each field, including modifications to the field name, data types, data to omit, etc. 
- [ ] open a PR the implements the plan (one table at a time)

**Comment by pdpinch** [comment]
@abeglova which tables did we decide to omit from this list?

**Comment by blarghmatey** [comment]
@pdpinch @abeglova can we close this?

**Comment by abeglova** [comment]
Closed!
