### ISSUE TITLE
Stage mitxonline courses_* tables

### ISSUE THREAD

**Issue by rachellougee** [mitodl/ol-data-platform#380]
# User Story
Stage data from mtixonline `courses_*` tables, so the data is clean and we can combine them into a denormalized place
omit user-related tables for now

- [x] #381
- [x] #386
- [x] #382
- [x] #383
- [x] #384
- [x] #385
- [x] Stage mitxonline `courses_programrun`

# Acceptance Criteria
- [ ]  list all `courses_*` tables we need to staging
- [ ]  what are the raw fields
- [ ]  write up a plan for each field, including modifications to the field name, data types, data to omit, etc.
- [ ]  open a PR that implements the plan

**Comment by rachellougee** [comment]
![image](https://user-images.githubusercontent.com/3138890/195679480-af8ea0fe-9913-45c3-8382-f117411fc631.png)
This is all the courses_* tables on mitxonline
Omitting any user-related tables, there are 7 tables we need to stage
I will work on these one by one

**Comment by rachellougee** [comment]
Ah, I realized that we have already staged `courses_course`, `courses_courserun`, and `courserunenrollment`

**Comment by dseaton** [comment]
You should review and make updates to those tables where necessary. I did that a while back before we had staging guidelines.

Can you write out the list of tables? I count 5.

**Comment by dseaton** [comment]
Now that we have some certificates generated, `courses_courseruncertificate` would be useful. I assume this is an easy way to get certificate information, which will be useful on a number of fronts.

**Comment by rachellougee** [comment]
`courses_courseruncertificate` is tied to user enrollment and grade, if we want to bring in the user's course certificates, we might need to bring in enrollment and grade as well, I just worked on migrating the user's DEDP course certificate from MicroMaster, the certificate information is mostly in wagtail CMS

**Comment by dseaton** [comment]
Ah - good point! You could definitely wait until we are working on enrollments.

**Comment by dseaton** [comment]
@rachellougee Is this done? We can close it if so.
