### ISSUE TITLE
Load edX tracking logs into data lake

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-data-platform#640]
# User Story
- As an analytics engineer I would like to incorporate user activity data into Open edX reports
- As a marketer I would like to identify users who have engaged with an Open edX course in a certain way
- As a course designer/instructor I would like to know how learners are interacting with my course material

# Description/Context
We currently send all tracking log data to S3 as newline delimited JSON files using a Vector agent on each edX instance. These logs are loaded into buckets that are created on a per-deployment/per-env basis. The naming structure is `<deployment_name>-<environment_stage>-edxapp-tracking` and the logs are loaded into a `/logs` path prefix.

Airbyte allows for treating these S3 buckets as a data source which we can then load into the data lake to our default destination. This allows us to treat this data in the same fashion as all of our other data sources, reducing any variance in the overall workflow for this data.

# Acceptance Criteria
- [ ] All tracking log data is loaded into the data lake for both QA and Production

```[tasklist]
# Tasks
- [x] Identify the core schema that we want to set as the `manually enforced schema` in the S3 source connector
- [x] Create source definitions for each of the tracking log source buckets that we want to integrate
  - [ ] mitx
  - [ ] xpro
  - [ ] mitxonline
- [ ] Tracking log sources are connected to the S3 glue destination and configured for incremental sync
```

**Comment by quazi-h** [comment]
I was able to pass in a manually enforced schema and get a successful sync going but when querying the table in the data lake, I have been getting errors about values: "fieldValue should not be null". Trying different iterations of the schema by marking some of the source fields with the "null" type and also running on a smaller subset of files or a single file with known fields to see if I can resolve the error.

**Comment by quazi-h** [comment]
When I do get a successful sync, I see that a lot less records are committed than the number of records in the tracking log. Example, I try to run the sync on a single file that contains 29171 records but when the sync runs, it tells me that a lot less records made it through: `252 emitted records252 committed records`. Still getting the null value issue though when I try to query the table in the data lake.

**Comment by quazi-h** [comment]
Due to an error in the upstream S3 Glue connector, the actual data in the destination was being captured in _airbyte_data as a JSON document whereas the schema is expecting it to be flattened. Our destination connector should be flattening the data in the JSON document that it writes. @blarghmatey opened an upstream PR to properly update the S3 connector config object: https://github.com/airbytehq/airbyte/pull/25048 to unblock this and it has been reviewed and merged.

**Comment by quazi-h** [comment]
We have created an upstream PR against the official Airbyte code https://github.com/airbytehq/airbyte/pull/25769/files with a solution to handle nested json objects. Users can enable a "stringify" option under the S3 and S3 Glue destination connector settings that will ensure that any nested objects are converted to strings when written to the final destination. We are waiting  for feedback and approval from the Airbyte team to merge these changes but we decided to point our own Airbyte connections to using our fork of Airbyte instead of the upstream one. This will ensure that any changes and fixes we make can be rolled out to our pipelines as soon as possible without having to wait for Airbyte's release process. We have already updated the Airbyte connections in QA to point to our fork and will update the production connections after confirming a successful pipeline run.

**Comment by quazi-h** [comment]
The next steps are:
1. Add the remaining tracking log sources and create connections in QA and Prod
2. Merge the changes in my branch (https://github.com/mitodl/airbyte/tree/640-add-stringify-json-option-s3) to our fork's master branch
3. Confirm that the QA connections were all successful after switching them to using our Airbyte fork
4. Update the Prod connections to point to our Airbyte fork

**Comment by quazi-h** [comment]
All tracking log sources have been added to QA.
We have xPro QA data and should have MITx and MITx Online QA data by tomorrow.
I also set up the xPro connection in PROD and it is currently syncing, should be complete by tomorrow.
I am still working on adding MITx and MITx Online sources to PROD, need to troubleshoot errors I'm seeing when adding those sources.

**Comment by quazi-h** [comment]
xPro tracking logs have successfully been ingested in Production.
The table **ol_data_lake_production.ol_warehouse_production_raw.raw__xpro__openedx__tracking_logs**  contains 107,601,744 records.

**Comment by pdpinch** [comment]
What's next? Do we need to stage the data?

**Comment by quazi-h** [comment]
Upon further investigation, we found that the nulls for those objects were coming from the source-s3, not the destination connector. https://github.com/mitodl/ol-data-platform/issues/737 was created to resolve differences between tracking log formats. The plan is to have a new script that will handle processing the legacy FluentD files to ensure integer timestamps are converted to strings. Tobias has made the needed changes to handle the top level json parsing for the vector logs: https://github.com/mitodl/ol-infrastructure/pull/1588.
